/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.lang.*;

public class AdminPanel extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form AdminPanel
     */
    private EComData adminData;
    
    public AdminPanel() {
        initComponents();
        
        adminData = ECommerce.myData;
        
        userRBtn.setActionCommand("user");
        userRBtn.addActionListener(this);
        
        itemRBtn.setActionCommand("item");
        itemRBtn.addActionListener(this);
        
        reviewRBtn.setActionCommand("review");
        reviewRBtn.addActionListener(this);
           
    }
    
    public void actionPerformed(ActionEvent evt)
    {
        String myAction = evt.getActionCommand();
        
        if (myAction.equals("user"))
        {
            importUserData();
        }
        else if (myAction.equals("item"))
        {
            importItemData();
        }
        else if (myAction.equals("review"))
        {
            importReviewData();
        }
    }
    
    public void importUserData()
    {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null, null}
                },
                new String [] {
                    "Delete",
                    "E-Mail",
                    "Password",
                    "Password Hint",
                    "First Name",
                    "Last Name"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Boolean.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
    }
    
    public void importItemData()
    {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null}
                },
                new String [] {
                    "Delete",
                    "Name",
                    "Description",
                    "Photo Path",
                    "Price"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Boolean.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
    }
    
    public void importReviewData()
    {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null}
                },
                new String [] {
                    "Delete",
                    "ReviewID",
                    "Name",
                    "Review Text",
                    "Rating"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Boolean.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userRBtn = new javax.swing.JRadioButton();
        itemRBtn = new javax.swing.JRadioButton();
        reviewRBtn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delete", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        buttonGroup1.add(userRBtn);
        userRBtn.setText("Users");

        buttonGroup1.add(itemRBtn);
        itemRBtn.setText("Items");

        buttonGroup1.add(reviewRBtn);
        reviewRBtn.setText("Reviews");

        submitBtn.setText("Submit");
        submitBtn.setToolTipText("");

        titleLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLbl.setText("Admin Console");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(userRBtn)
                        .addGap(18, 18, 18)
                        .addComponent(itemRBtn)
                        .addGap(18, 18, 18)
                        .addComponent(reviewRBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(titleLbl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userRBtn)
                    .addComponent(itemRBtn)
                    .addComponent(reviewRBtn)
                    .addComponent(submitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton itemRBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton reviewRBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JRadioButton userRBtn;
    // End of variables declaration//GEN-END:variables
}
