/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Matt
 */
public class ECommerce extends javax.swing.JFrame {

    
    //Globals
    public static EComData myData;
    public static User currentUser;
    
    
    /**
     * Creates new form EComm
     */
    public ECommerce() {
        myData = new EComData();
        
        initComponents();
        
        //Application Title
        setTitle("ECommerce Application");
        
        setResizable(false);
        
        adminBtn.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                adminConsole();
            }
        });
    }
    
    public static void enableAdmin()
    {
        adminBtn.setVisible(true);
        adminBtn.setEnabled(true);
    }
    
    public static void signout()
    {
        adminBtn.setVisible(false);
        adminBtn.setEnabled(false);
        adminPanel1.setVisible(false);
        itemPanel2.setVisible(false);
    }
    
    private void adminConsole()
    {
        adminPanel1.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel1 = new ecommerce.NavigationPanel();
        headerPanel1 = new ecommerce.HeaderPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        signInPanel1 = new ecommerce.SignInPanel();
        registerPanel1 = new ecommerce.RegisterPanel();
        adminPanel1 = new ecommerce.AdminPanel();
        adminBtn = new javax.swing.JButton();
        itemPanel2 = new ecommerce.ItemPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signInPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signInPanel1.setBounds(220, 150, 436, 184);
        jLayeredPane1.add(signInPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        //Hide form
        signInPanel1.setVisible(false);

        registerPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerPanel1.setBounds(210, 80, 454, 377);
        jLayeredPane1.add(registerPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        registerPanel1.setVisible(false);
        adminPanel1.setBounds(10, 10, 850, 530);
        jLayeredPane1.add(adminPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminPanel1.setVisible(false);

        adminBtn.setText("Admin");
        adminBtn.setBounds(10, 560, 90, 40);
        jLayeredPane1.add(adminBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminBtn.setVisible(false);
        adminBtn.setEnabled(false);

        itemPanel2.setName(""); // NOI18N
        itemPanel2.setBounds(10, 10, 850, 580);
        jLayeredPane1.add(itemPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        itemPanel2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECommerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECommerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECommerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECommerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECommerce().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton adminBtn;
    public static ecommerce.AdminPanel adminPanel1;
    private ecommerce.HeaderPanel headerPanel1;
    public static ecommerce.ItemPanel itemPanel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private ecommerce.NavigationPanel navigationPanel1;
    public static ecommerce.RegisterPanel registerPanel1;
    public static ecommerce.SignInPanel signInPanel1;
    // End of variables declaration//GEN-END:variables
}
